# Generated by Django 5.2.17 on 2026-08-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readings', '0001_initial'),
        ('tariffs', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=60, unique=True)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('energy_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='readings.billingperiod')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='readings.meterreading')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='tariffs.tariff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='tenants.tenant')),
            ],
        ),
    ]
