# Generated by Django 5.2.17 on 2026-08-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAULTY', 'Faulty')], default='ACTIVE', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('initial_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='meter', to='properties.room')),
            ],
        ),
    ]
